Add logs testing (#11)
* feat: setup add setup for logs endpoint testing

* feat: added /log/event testing

* feat: added /log/transfer testing

* fix: update wallet init

* update pagination tests

* fix wait for wallet funding

* update pagination tests

* fix: wait for funding

* feat: use aws hosted runners

* test: check reliability

* test: disable spot instances

* test: disable spot instances

* test: throttled requests

* test: throttled requests

* test: throttled requests

* test: throttled requests

* feat: enable workflow_call

* fix: gh actions

* fix: remove concurrency

* feat: add jest-expect-message

* fix: update jest config

* chore: update gh actions

* chore: update gh actions

* chore: update gh actions

* fix: update hardhat contract call

* revert bad f&r

* fix: update runs-on

* fix: wait for chain and print logs

* fix: update tests to run against thor solo

* feat: add tests to set range to null

* fix: updates for PR comments

* chore: refactor tests to use a common flow

* chore: update gh actions

* feat: add max/min limit tests

* chore: cleanup unused code

* fix: broken jest config

* chore: update readme to include details about THOR_IMAGE

* chore: update thor.yaml url and run yarn format

diff --git a/.github/workflows/run-e2e-tests.yaml b/.github/workflows/run-e2e-tests.yaml
--- a/.github/workflows/run-e2e-tests.yaml
+++ b/.github/workflows/run-e2e-tests.yaml
@@ -1,55 +1,48 @@
 name: E2E Tests
 
 on:
-  pull_request:
-    branches:
-      - main
-  push:
-    branches:
-      - main
+    workflow_dispatch:
+    workflow_call:
+    push:
+        branches:
+            - main
+    pull_request:
+        branches:
+            - main
 
 permissions:
-  checks: write
-  pull-requests: write
-
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}-run-e2e-tests
-  cancel-in-progress: true
+    checks: write
+    pull-requests: write
 
 jobs:
-  e2e_tests:
-    name: Run E2E Tests
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+    e2e_tests:
+        name: Run E2E Tests
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
 
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
+            - name: Setup Node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 20
 
-      - name: Install Node Modules
-        run: yarn install
+            - name: Install Node Modules
+              run: yarn install
 
-      - name: Run Tests
-        run: yarn test
+            - name: Run Tests
+              run: yarn test
 
-      - name: Publish Results
-        uses: dorny/test-reporter@v1
-        id: test-reporter
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: E2E Test Report
-          only-summary: 'false'
-          list-suites: 'all'
-          list-tests: 'all'
-          fail-on-error: 'true'
-          reporter: 'jest-junit'
-          path: |
-            junit.xml
-
-        # TODO: Add PR Comment
-      - name: Add PR Comment
-        run: |
-          echo ${{steps.test-reporter.outputs.url_html}}
+            - name: Publish Results
+              uses: dorny/test-reporter@v1
+              id: test-reporter
+              if: success() || failure() # run this step even if previous step failed
+              with:
+                  name: E2E Test Report
+                  only-summary: 'false'
+                  list-suites: 'all'
+                  list-tests: 'all'
+                  fail-on-error: 'true'
+                  reporter: 'jest-junit'
+                  path: |
+                      junit.xml
